#!/bin/bash
set -uex
set -o pipefail

REPO=/etc/yum.repos.d/dib-ci-pcs6.repo

mv /etc/yum.repos.d/parallels-cloud-server.repo /etc/yum.repos.d/parallels-cloud-server.repo.old

cat - > $REPO <<EOF

# repositories with Parallels Software should start with 'parallels-' prefix (for PVA)
[parallels-cloud-server]
name=Parallels Cloud Server Base
mirrorlist=http://repo.eng.sw.ru/mirrors/psbm/6.0/update9/validated
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/PARALLELS_GPG_KEY
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CloudLinux

EOF

yum update -y --disablerepo=* --enablerepo=parallels-cloud-server

# before installing linux-rootfs-resize we need to leave only one kernel in /boot
ls -1v /boot/vmlinuz-* | head -1 | xargs rm -f
ls -1v /boot/initramfs-* | head -1 | xargs rm -f
ls -1v /boot/vmlinuz-*-mod | head -1 | xargs rm -f
ls -1v /boot/initramfs-*-mod | head -1 | xargs rm -f

cd /tmp
[ -d linux-rootfs-resize ] || git clone https://github.com/flegmatik/linux-rootfs-resize.git
cd linux-rootfs-resize
./install

ls -1 /boot
